### ISSUE TITLE
Add more information on test structure

### ISSUE THREAD

**Issue by joshlynchONS** [best-practice-and-impact/qa-of-code-guidance#128]
Add more information on how to structure tests. For example:
* when should use you test classes (what are the benefits)
* test file per module or function
* best way to write tests
* where should your tests file be
* the importance of importing your package
* etc...

**Comment by sarahcollyer** [comment]
There is an existing subsection on structuring test files that has started to touch on the above. I would recommend taking what has already been written there and expanding it to include the above bullet points, so that it covers structuring your files **and** the tests themselves. This can then feed in to the subsections on unit tests, integration tests, and end-to-end testing.

**DoD: Structuring subsection has been expanded to include both file and test structure**
