### ISSUE TITLE
Dead link on page /continuous_integration.html

### ISSUE THREAD

**Issue by foster999** [best-practice-and-impact/qa-of-code-guidance#150]
Link is dead for [PATRICK’S SOFTWARE BLOG](https://www.patricksoftwareblog.com/setting-up-gitlab-ci-for-a-python-application/)

**Comment by foster999** [comment]
We should also see if using the [sphinx external link checker](https://www.sphinx-doc.org/en/master/usage/builders/index.html#sphinx.builders.linkcheck.CheckExternalLinksBuilder) would detect these for us in CI. Think this can be used via `sphinx-build -b linkcheck`

**Comment by Jacobb164** [comment]
Govcookiecutter had problemswith sphinx external link checker on ONS computers due to timing our with HTTPS links. Instead Govcookiecutter uses https://github.com/gaurav-nelson/github-action-markdown-link-check

**Comment by sarahcollyer** [comment]
Have looked at the blog to see if maybe it's just that the url has changed, but it looks like the actual post has been deleted. We should try and replace with a link to another example if we can find one that is suitable.

**DoD**

- [ ] Link has been replaced with an alternative example and works.

**Comment by ellie-o** [comment]
Original post has been found using Internet Archive's WayBack Machine: [Setting up a GitLab CI for a Python application](https://web.archive.org/web/20230321180431/https://www.patricksoftwareblog.com/setting-up-gitlab-ci-for-a-python-application/). Have looked at the current blog and Patrick's X, and both have been fairly inactive since mid 2023/early 2024. Have also searched the website Patrick writes for (testdriven.io) for anything about CI in GitLab for Python.

This post has been copied to someone else's repo, but with no credit to the original, so unsure if this is the best thing to replace it: [nekrasovp.github.io](https://nekrasovp.github.io/setting-up-gitlab-ci.html).

Have found several alternatives to get peer reviewed as a replacement:
[How to Set Up CI/CD for Python Builds on GitLab](https://www.activestate.com/blog/how-to-set-up-ci-cd-for-python-on-gitlab/)
[The Ultimate Guide to GitLab CI/CD: Along with Example of Building CI/CD Pipeline for Python](https://medium.com/@almaswebconsulting/the-ultimate-guide-to-gitlab-ci-cd-along-with-example-of-building-ci-cd-pipeline-for-python-8d2ca26aff7f)

**Comment by giro090** [comment]
Thanks for finding these alternatives Ellie. :) I'm a fan of the Patrick's software blog link because it covers other things in this chapter - if we use that, I suggest we use the Wayback Machine link to it to ensure appropriate credit.
