### ISSUE TITLE
Version control page getting blocked by firewalls

### ISSUE THREAD

**Issue by MKatz-DHSC** [best-practice-and-impact/qa-of-code-guidance#83]
When viewing the book, I cannot access the https://best-practice-and-impact.github.io/qa-of-code-guidance/version_control.html page as it is blocked by the Department of Health and Social Care firewall.

I have queried with our IT services and it seems that the page has a "bad reputation" and was found to be malicious at some point by various vendors (see reports for the page on https://www.virustotal.com/). They have also shared another report with me that states the page is being flagged as previously is was thought to be part of a botnet.

Not sure how to solve this issue or what exactly on the page is causing the problem but might be worth investigating as the page owner.

**Comment by foster999** [comment]
This duplicates #71, but is a reoccurring issue with various departments.

I suspect that it's caused by text that describes how to handle information breaches via version control. But as none of the content is genuinely malicious, we can't really action this unless security from one of these departments can detail the cause.

**Comment by ailsaprise** [comment]
Just to add to this that the DHSC IT security thing iBoss has now blocked the entire site (not just the version control page) as it believes it is malware. Is there any way to fix this? Happy to ask our IT for any useful info they might have.
